In [1]:
#kütüphaneler
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn
from sklearn.metrics import r2_score 
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [2]:
#veri yükleme
dataFrame = pd.read_csv('Titanic.csv')

In [3]:
dataFrame

Survived  Pclass                                               Name  \
0           0       3                             Mr. Owen Harris Braund   
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2           1       3                              Miss. Laina Heikkinen   
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4           0       3                            Mr. William Henry Allen   
..        ...     ...                                                ...   
882         0       2                               Rev. Juozas Montvila   
883         1       1                        Miss. Margaret Edith Graham   
884         0       3                     Miss. Catherine Helen Johnston   
885         1       1                               Mr. Karl Howell Behr   
886         0       3                                 Mr. Patrick Dooley   

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0      male  22.0                        1                        0   7.2500  
1    female  38.0                        1                        0  71.2833  
2    female  26.0                        0                        0   7.9250  
3    female  35.0                        1                        0  53.1000  
4      male  35.0                        0                        0   8.0500  
..      ...   ...                      ...                      ...      ...  
882    male  27.0                        0                        0  13.0000  
883  female  19.0                        0                        0  30.0000  
884  female   7.0                        1                        2  23.4500  
885    male  26.0                        0                        0  30.0000  
886    male  32.0                        0                        0   7.7500  

[887 rows x 8 columns]

In [4]:
dataFrame.describe()

Survived      Pclass         Age  Siblings/Spouses Aboard  \
count  887.000000  887.000000  887.000000               887.000000   
mean     0.385569    2.305524   29.471443                 0.525366   
std      0.487004    0.836662   14.121908                 1.104669   
min      0.000000    1.000000    0.420000                 0.000000   
25%      0.000000    2.000000   20.250000                 0.000000   
50%      0.000000    3.000000   28.000000                 0.000000   
75%      1.000000    3.000000   38.000000                 1.000000   
max      1.000000    3.000000   80.000000                 8.000000   

       Parents/Children Aboard       Fare  
count               887.000000  887.00000  
mean                  0.383315   32.30542  
std                   0.807466   49.78204  
min                   0.000000    0.00000  
25%                   0.000000    7.92500  
50%                   0.000000   14.45420  
75%                   0.000000   31.13750  
max                   6.000000  512.32920

In [5]:
dataFrame.isnull().sum()

Survived                   0
Pclass                     0
Name                       0
Sex                        0
Age                        0
Siblings/Spouses Aboard    0
Parents/Children Aboard    0
Fare                       0
dtype: int64

In [6]:
# EKSİK VERİ YOK

In [7]:
gender=dataFrame.iloc[:,3:4].values

In [8]:
gender

array([['male'],
       ['female'],
       ['female'],
       ['female'],
       ['male'],
       ['male'],
       ['male'],
       ['male'],
       ['female'],
       ['female'],
       ['female'],
       ['female'],
       ['male'],
       ['male'],
       ['female'],
       ['female'],
       ['male'],
       ['male'],
       ['female'],
       ['female'],
       ['male'],
       ['male'],
       ['female'],
       ['male'],
       ['female'],
       ['female'],
       ['male'],
       ['male'],
       ['female'],
       ['male'],
       ['male'],
       ['female'],
       ['female'],
       ['male'],
       ['male'],
       ['male'],
       ['male'],
       ['male'],
       ['female'],
       ['female'],
       ['female'],
       ['female'],
       ['female'],
       ['female'],
       ['male'],
       ['male'],
       ['female'],
       ['male'],
       ['female'],
       ['male'],
       ['male'],
       ['female'],
       ['female'],
       ['male'],
       ['male'],
       ['fe

In [9]:
le= preprocessing.LabelEncoder()

In [10]:
gender= le.fit_transform(gender)

C:\Users\dilar\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [11]:
# male=1  female=0
gender

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,

In [12]:
dataFrame["Sex"]=gender 

In [13]:
dataFrame.head()

Survived  Pclass                                               Name  Sex  \
0         0       3                             Mr. Owen Harris Braund    1   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...    0   
2         1       3                              Miss. Laina Heikkinen    0   
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle    0   
4         0       3                            Mr. William Henry Allen    1   

    Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0  22.0                        1                        0   7.2500  
1  38.0                        1                        0  71.2833  
2  26.0                        0                        0   7.9250  
3  35.0                        1                        0  53.1000  
4  35.0                        0                        0   8.0500

In [14]:
dataFrame=dataFrame.drop(columns=["Name"]) # name sütunu temizlendi

In [15]:
dataFrame

Survived  Pclass  Sex   Age  Siblings/Spouses Aboard  \
0           0       3    1  22.0                        1   
1           1       1    0  38.0                        1   
2           1       3    0  26.0                        0   
3           1       1    0  35.0                        1   
4           0       3    1  35.0                        0   
..        ...     ...  ...   ...                      ...   
882         0       2    1  27.0                        0   
883         1       1    0  19.0                        0   
884         0       3    0   7.0                        1   
885         1       1    1  26.0                        0   
886         0       3    1  32.0                        0   

     Parents/Children Aboard     Fare  
0                          0   7.2500  
1                          0  71.2833  
2                          0   7.9250  
3                          0  53.1000  
4                          0   8.0500  
..                       ...      ...  
882                        0  13.0000  
883                        0  30.0000  
884                        2  23.4500  
885                        0  30.0000  
886                        0   7.7500  

[887 rows x 7 columns]

In [16]:
# KNN REGRESSION

In [17]:
x=dataFrame.iloc[:,1:7].values #bağımlı değişken

In [18]:
y=dataFrame.iloc[:,0].values #bağımsız değişken

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=6)

In [20]:
sc=StandardScaler()

In [21]:
X_train=sc.fit_transform(x_train)

In [22]:
X_test=sc.transform(x_test)

In [23]:
knn= KNeighborsClassifier(n_neighbors=11,metric='minkowski')

In [24]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=11)

In [25]:
y_pred=knn.predict(X_test) # test_size->0.33 k->11 score->84.3

In [26]:
sayac=1
for k in range (1,15):
    knn_yeni= KNeighborsClassifier(n_neighbors=k)
    knn_yeni.fit(X_train,y_train)
    print(sayac,knn_yeni.score(X_test,y_test)*100)
    sayac+=1

1 75.76791808873719
2 77.47440273037543
3 83.27645051194538
4 81.91126279863481
5 82.93515358361775
6 79.18088737201366
7 82.5938566552901
8 82.93515358361775
9 83.27645051194538
10 81.56996587030717
11 84.30034129692832
12 80.54607508532423
13 83.61774744027304
14 82.5938566552901


In [27]:
knn.score(X_test,y_test)

0.8430034129692833

In [28]:
from sklearn.preprocessing import MinMaxScaler

In [29]:
sc = MinMaxScaler()

In [30]:
sc.fit_transform(x)

array([[1.        , 1.        , 0.27117366, 0.125     , 0.        ,
        0.01415106],
       [0.        , 0.        , 0.4722292 , 0.125     , 0.        ,
        0.13913574],
       [1.        , 0.        , 0.32143755, 0.        , 0.        ,
        0.01546857],
       ...,
       [1.        , 0.        , 0.08268409, 0.125     , 0.33333333,
        0.04577135],
       [0.        , 1.        , 0.32143755, 0.        , 0.        ,
        0.0585561 ],
       [1.        , 1.        , 0.39683338, 0.        , 0.        ,
        0.01512699]])

In [31]:
new_prediction = knn.predict(sc.transform(np.array([[3,1,27,0,0,8.4583]])))

In [32]:
new_prediction[0]

0

In [33]:
new_prediction = knn.predict(sc.transform(np.array([[2,0,23,0,0,13]])))

In [34]:
new_prediction[0]

0

In [35]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score 

In [36]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Doğruluk Oranı: {accuracy:.2f}")

Doğruluk Oranı: 0.84


In [553]:
# Linear Regression 

In [554]:
x=dataFrame.iloc[:,1:7].values #bağımlı değişken

In [555]:
y=dataFrame.iloc[:,0].values #bağımsız değişken

In [556]:
lin_reg= LinearRegression()

In [557]:
lin_reg.fit(x,y)

LinearRegression()

In [558]:
import statsmodels.api as sm 

In [559]:
model = sm.OLS(lin_reg.predict(x),x)

In [560]:
model.fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.766
Model:                            OLS   Adj. R-squared (uncentered):              0.764
Method:                 Least Squares   F-statistic:                              479.5
Date:                Sun, 22 Oct 2023   Prob (F-statistic):                   1.74e-273
Time:                        17:08:38   Log-Likelihood:                          12.486
No. Observations:                 887   AIC:                                     -12.97
Df Residuals:                     881   BIC:                                      15.75
Df Model:                           6                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.1374      0.007     20.136      0.000       0.124       0.151
x2            -0.4215      0.017    -24.217      0.000      -0.456      -0.387
x3             0.0068      0.000     13.946      0.000       0.006       0.008
x4            -0.0270      0.008     -3.259      0.001      -0.043      -0.011
x5             0.0017      0.011      0.151      0.880      -0.021       0.024
x6             0.0035      0.000     19.750      0.000       0.003       0.004
==============================================================================
Omnibus:                       45.229   Durbin-Watson:                   1.933
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               94.793
Skew:                          -0.313   Prob(JB):                     2.61e-21
Kurtosis:                       4.474   Cond. No.                         140.
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [561]:
# Logistic Regression

In [562]:
x=dataFrame.iloc[:,1:7].values #bağımlı değişken

In [563]:
y=dataFrame.iloc[:,0].values #bağımsız değişken

In [580]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.44,random_state=5)

In [581]:
sc=StandardScaler()

In [582]:
X_train=sc.fit_transform(x_train)

In [583]:
X_test=sc.transform(x_test)

In [584]:
logr= LogisticRegression(random_state=0)

In [585]:
logr.fit(X_train,y_train) #eğitilmiş model

LogisticRegression(random_state=0)

In [586]:
logr.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [587]:
y_pred=logr.predict(X_test)  #eğitilmiş metoda predict etmesini söylüyor

In [588]:
y_pred

array([1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,

In [589]:
y_test

array([1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,

In [597]:
logr.score(X_test,y_test) # randomstate->11 score-> 82

0.8184143222506394

In [598]:
from sklearn.metrics import confusion_matrix #confusion matrix classı import edildi

In [599]:
cm = confusion_matrix(y_test,y_pred) #confusion matrix objesi oluşturuldu

In [600]:
cm

array([[223,  27],
       [ 44,  97]], dtype=int64)

In [601]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score 

In [602]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Doğruluk Oranı: {accuracy:.2f}")

Doğruluk Oranı: 0.82


In [ ]:
#### RANDOM FOREST 

In [37]:
from sklearn.preprocessing import StandardScaler

In [38]:
sc =preprocessing.StandardScaler()

In [39]:
from sklearn.model_selection import train_test_split 


In [249]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.44, random_state= 10)

In [250]:
X_train=sc.fit_transform(x_train)

In [251]:
X_test=sc.transform(x_test)

In [252]:
from sklearn.ensemble import RandomForestClassifier

In [253]:
from sklearn.pipeline import Pipeline

In [254]:
classifier = RandomForestClassifier(random_state=0)

In [255]:
classifier.fit(X_train,y_train)

RandomForestClassifier(random_state=0)

In [256]:
y_pred = classifier.predict(X_test)

In [257]:
from sklearn.metrics import confusion_matrix

In [258]:
cm = confusion_matrix(y_test,y_pred)

In [259]:
cm

array([[215,  29],
       [ 39, 108]], dtype=int64)

In [260]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

In [261]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Doğruluk Oranı: {accuracy:.2f}")

r2 = r2_score(y_test, y_pred)
print(f"R^2 Skoru: {r2:.2f}")

mae = mean_absolute_error(y_test, y_pred)
print(f"Mean Absolute Error (MAE): {mae:.2f}")

mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error (MSE): {mse:.2f}")

rmse = np.sqrt(mse)
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")

Doğruluk Oranı: 0.83
R^2 Skoru: 0.26
Mean Absolute Error (MAE): 0.17
Mean Squared Error (MSE): 0.17
Root Mean Squared Error (RMSE): 0.42


In [262]:
# test_size=0.33   random_state=100  random_state=0 ---->0.83
# test_size=0.44  random_state=10 random_state=0 ---->0.83